version: '3.8'

services:
  db:
    image: postgres:13
    container_name: pets_food_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pets_food
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pets_food"]
      interval: 5s
      timeout: 5s
      retries: 10

  bot:
    build: ./bot
    container_name: telegram_bot
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./bot:/app
    restart: always

volumes:
  postgres_data: